const types = {
  LOAD_PRODUCTS_REQUEST: 'LOAD_PRODUCTS_REQUEST',
  LOAD_PRODUCTS_SUCCESS: 'LOAD_PRODUCTS_SUCCESS',
  LOAD_PRODUCTS_FAILURE: 'LOAD_PRODUCTS_FAILURE',
  SEARCH_FOR_PRODUCT: 'SEARCH_FOR_PRODUCT'
};

export default types;
